Global disable second_level_cache
monsterstrike/second_level_cache pull request #9
Opened 2019-08-15 08:35 UTC by KumatomatomaKu

global switch

2019-08-15 08:51 UTC, genkami approved these changes
:yosasou:

2019-08-15 09:46 UTC, fumihiroito requested changes

2019-08-15 09:46 UTC, fumihiroito commented on lib/second_level_cache.rb
> +  def self.without_second_level_cache
```
SecondLevelCache.without_second_level_cache do
  Book.find(1)
end
```

のようになってしまって `second_level_cache` が冗長なので名前の変更を検討してください。
例えば `SecondLevelCache.without_cache` のようになっていれば良いと思います。

2019-08-20 10:32 UTC, KumatomatomaKu commented on lib/second_level_cache.rb
> +  def self.without_second_level_cache
mixinではない部分からsecond_level_cacheのprefixを省略した

2019-08-21 02:34 UTC, fumihiroito commented
SecondLevelCacheが有効になってない時に `fetch_by_index` を呼ばれてしまわないように `ArgumentError` がraiseされているのでその挙動は変えたくありません。

`without_cache` を `conservative` としてread/writeはキャッシュを参照せずinvalidateはする、という動作になっていた方がよさそうだと思いました。

2019-08-21 03:22 UTC, KumatomatomaKu commented
そうしたいのはわかります、がともなればそれは `without_cache` ではないですね、一応 `with` してる

2019-08-21 10:43 UTC, fumihiroito commented
その通り。
だから `without_cache` という名前を変えて動作も変えようという提案をしています。

2019-08-22 01:11 UTC, KumatomatomaKu commented
ちょっと考えた。
* read/writeしないのはいいけどいろんなところにif分を足しまくるのも不毛なのでそういうメソッドが必要、とそこまで思って、そもそもじゃぁキャッシュのread/writeが一切して欲しくないならcache_storeから手を入れればいいのでは？WriteThroughLocalCacheやDoubleWriteのするように、SLCは触らなくて済むし、いかなるキャッシュの使用も本当の意味でガードされる。現状だとこれはoff、あれはoffって言うけど、直接`cache_store.get` でも叩かれたら法外になる。
* invalidateを残す理由として認識してるのは、今回の目的は信用できなくなったキャッシュの値を文字通り信用せずとも、それを正す機会があればする、にあると思うけど。それだったらwriteを残すのも検討の余地がある、と言うのもinvalidateせずそのまま新しい値を上書きするパターンもなくはないので、writeしないってことはそれらはそのまま残るから、目的からしたら対策は不完全

2019-08-23 03:44 UTC, fumihiroito commented
> cache_storeから手を入れればいいのでは？

Good idea!

> writeを残すのも検討の余地

保守的な動作をするので新しい値を書き込むのは別のプロセスに任せるというのはどうだろう。
キャッシュなので `update_second_level_cache` で新しい値を書いたとしても別のところで永続化されているので、消しておけば求める状態になるはず。
ここでの責任範囲はそこまでで、もう一度値をキャッシュする時不整合が起きてしまうのであればそれはキャッシュする側の問題かアプリケーション側の問題で、ここの責任ではない。

2019-08-26 10:55 UTC, KumatomatomaKu commented
closing this

cache_store主導の実装を考え直す

2019-08-26 10:55 UTC, closed without merging